#ifndef MINECRAFT_J_JSONNODEDOESNOTMATCHCHAINEDJSONNODESELECTOREXCEPTION_HPP
#define MINECRAFT_J_JSONNODEDOESNOTMATCHCHAINEDJSONNODESELECTOREXCEPTION_HPP

namespace Minecraft
{
	class J_JsonNodeDoesNotMatchChainedJsonNodeSelectorException
	{

	};
}

#endif